### ISSUE TITLE
Large vertical spacer in settings dialog

### ISSUE THREAD

**Issue by flerro** [paullinuxthemer/Nextwaita#7]
Hi, 

thanks for the theme, I really like it!

On Ubuntu 19.04 / GNOME Shell 3.32.0, the vertical spacer between other components in the settings dialog window is too large.

![2019-06-11_12-47](https://user-images.githubusercontent.com/593048/59266299-9d3b8100-8c47-11e9-8157-862ce67790af.png)

FYI other windows with similar layout look fine instead (e.g. Tweak UI).

![image](https://user-images.githubusercontent.com/593048/59267628-fce75b80-8c4a-11e9-8686-1357e6eff381.png)

**Comment by mld9401** [comment]
Same problem with me.

**Comment by endlesskwazar** [comment]
Same with me. Ubuntu 19.10 vanilla gnome session 3.34.1

**Comment by wep777** [comment]
gtk.css

make change 

from

min-width: 12.375rem; /*180px;*/

to

min-width: 1px;

Enjoy

**Comment by flerro** [comment]
@wep777 Thanks! It works!
